apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: c6kb04h8h-python 
  janus-idp.io/tekton: c6kb04h8h-python
  backstage.io/kubernetes-id: c6kb04h8h-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c6kb04h8h-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml