apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: c6kb04h8h-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:e7c7166d47cd423825f5f3538eeb5bb72b1d72b7@sha256:9e82de14b5f882b24b6b6c78f192204fc2cae6bda02cc5ad6543fdecfe95d0bb
          name: container-image
